---
title: Werk de tekst in een TextMeshPro GameObject bij
hero_image: images/banner.png
description: Werk de tekst in een TextMeshPro GameObject bij
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - title: Werk de tekst in een TextMeshPro GameObject bij
