title: Update the text in a TextMeshPro GameObject
hero_image: images/banner.png
description: Update the text in a TextMeshPro GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Update the text in a TextMeshPro GameObject
